### ISSUE TITLE
Move to `dcc-utils`

### ISSUE THREAD

**Issue by M4GNV5** [M4GNV5/Vaccimon#10]
eudgc seems to be broken with some certificates and we could not even build it from source.

This library seems to support the broken certs and have overall better code quality: https://github.com/Path-Check/dcc-sdk.js

**Comment by alexhorn** [comment]
Sounds good, doesn't work.

**Comment by alexhorn** [comment]
Maybe we could try this instead: https://github.com/ministero-salute/dcc-utils

**Comment by M4GNV5** [comment]
What is the reason for it to not work? There is an `unpackAndVerify` function which should do what we need?

But you are right, the dcc-utils repo seems like the correct choice

**Comment by alexhorn** [comment]
dcc-sdk.js is built for node and does not work in the browser

**Comment by M4GNV5** [comment]
I guess we can close this, now that we found a way to add the new CA json to eudgc
