### ISSUE TITLE
Generate faces in the frontend

### ISSUE THREAD

**Issue by M4GNV5** [M4GNV5/Vaccimon#9]
Currently face images are loaded from an external server. We could imrpove performance, reduce data usage and increase privacy by embedding the face generation into the frontend itself.

**Comment by WebFreak001** [comment]
images: https://github.com/itsthatguy/avatars-api-middleware/tree/develop/src/img

**Comment by M4GNV5** [comment]
performance wise we should probably bundle these into a single file?
Either via a texture map like file (software overhead?) or via a CSS file with base64 images (slower).

**Comment by M4GNV5** [comment]
Since 4472ea7c72d2387611bd6714de4cbd4faf45672e we use our self-hosted version of the faces API. Even though this issue would still be a nice addition the current state is good enough for me, so ill close this issue.
